### ISSUE TITLE
TS support

### ISSUE THREAD

**Issue by guitarhero17** [asbjornh/react-tiny-collapse#4]
Hi, thank you for this library!

Finally I've found something which is lightweight and takes care of a dynamic children height.  Most of the other libraries only update on open/close.

Is a TS support planned soon enough? I'd like to use the library in a production environment where all of the other code was rewritten in TS.

Thanks.

**Comment by asbjornh** [comment]
Hey! Glad you find it useful.

I hadn't really planned on that, but I published something similar for `react-tiny-crossfade` today so I decided to do the same for this lib. v2.0.0 should be available on npm now.

Let me know if you encounter any type-related issues with the new version ✌️
